[pytest]
DJANGO_SETTINGS_MODULE = config.settings
pythonpath = .
testpaths = tests

markers =
    slow: marks tests as slow
    integration: marks tests as integration tests
    unit: marks tests as unit tests
