# Generated by Django 5.2.8 on 2025-11-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка на статью')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('source', models.CharField(default='Lenta.ru', max_length=100, verbose_name='Источник')),
                ('category', models.CharField(default='russia', max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
            ],
            options={
                'verbose_name': 'RSS Новость',
                'verbose_name_plural': 'RSS Новости',
                'ordering': ['-published_at'],
            },
        ),
    ]
