# Generated by Django 5.2.8 on 2025-12-15 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rssnews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.URLField(verbose_name='Ссылка на статью')),
                ('reaction_type', models.CharField(choices=[('important', '🔥 важно'), ('interesting', '🤔 интересно'), ('shocking', '😱 шокирует'), ('useful', '💡 полезно'), ('liked', '❤️ нравится')], max_length=20, verbose_name='Тип реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реакция',
                'verbose_name_plural': 'Реакции',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article_url')},
            },
        ),
    ]
