"""add_created_at

Revision ID: 656540c959c2
Revises: 3ca0b0c6a2ac
Create Date: 2026-03-23 09:51:15.740685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '656540c959c2'
down_revision: Union[str, Sequence[str], None] = '3ca0b0c6a2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('news', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('news', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('news', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_news_category'), 'news', ['category'], unique=False)
    op.create_index('ix_news_category_published', 'news', ['category', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_category_published', table_name='news')
    op.drop_index(op.f('ix_news_category'), table_name='news')
    op.alter_column('news', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('news', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('news', 'updated_at')
    op.drop_column('news', 'created_at')
    # ### end Alembic commands ###
